LibraryWebApplication/User.Interface.Layer/Controllers/AuthorsController.cs
using Data.Access.Layer.Classes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Layer.Abstraction;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace User.Interface.Layer.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ILogger<AuthorsController> _logger;
        private IUnitOfWork _uOw;

        public AuthorsController(ILogger<AuthorsController> logger, IUnitOfWork uOw)
        {
            _logger = logger;
            _uOw = uOw;
        }
        // GET: AuthorsController
        public ActionResult Index()
        {
            IEnumerable<Authors> authors = _uOw.AuthorRepository.GetAllAsync().GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(authors);
        }

        // GET: AuthorsController/Details/5
        public ActionResult Details(int id)
        {
            Authors author = _uOw.AuthorRepository.GetByIdAsync(id).GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(author);
        }

        // GET: AuthorsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AuthorsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Authors author)
        {
            try
            {
                _uOw.AuthorRepository.AddAsync(author).GetAwaiter().GetResult();
                _uOw.CommitAsync().GetAwaiter().GetResult();
                _uOw.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorsController/Edit/5
        public ActionResult Edit(int id)
        {
            Authors author = _uOw.AuthorRepository.GetByIdAsync(id).GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(author);
        }

        // POST: AuthorsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Authors author)
        {
            try
            {
                _uOw.AuthorRepository.UpdateAsync(author).GetAwaiter().GetResult();
                _uOw.CommitAsync().GetAwaiter().GetResult();
                _uOw.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryWebApplication/User.Interface.Layer/Controllers/BooksController.cs
using Data.Access.Layer.Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Layer.Abstraction;
using System.Collections.Generic;

namespace User.Interface.Layer.Controllers
{
    public class BooksController : Controller
    {
        private readonly ILogger<BooksController> _logger;
        private IUnitOfWork _uOw;

        public BooksController(ILogger<BooksController> logger, IUnitOfWork uOw)
        {
            _logger = logger;
            _uOw = uOw;
        }
        // GET: BooksController
        public ActionResult Index()
        {
            IEnumerable<Books> books = _uOw.BookRepository.GetAllWithAuthorAsync().GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(books);
        }

        // GET: BooksController/Details/5
        public ActionResult Details(int id)
        {
            Books book = _uOw.BookRepository.GetByIdWithAuthorAsync(id).GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(book);
        }

        // GET: BooksController/Create
        public ActionResult Create()
        {
            ViewBag.Authors = _uOw.AuthorRepository.GetAllAsync().GetAwaiter().GetResult();
            return View();
        }

        // POST: BooksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Books book)
        {
            try
            {
                _uOw.BookRepository.AddAsync(book).GetAwaiter().GetResult();
                _uOw.CommitAsync().GetAwaiter().GetResult();
                _uOw.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BooksController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Authors = _uOw.AuthorRepository.GetAllAsync().GetAwaiter().GetResult();
            Books book = _uOw.BookRepository.GetByIdAsync(id).GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(book);
        }

        // POST: BooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Books book)
        {
            try
            {
                _uOw.BookRepository.UpdateAsync(book).GetAwaiter().GetResult();
                _uOw.CommitAsync().GetAwaiter().GetResult();
                _uOw.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryWebApplication/User.Interface.Layer/Controllers/ReportController.cs
using Data.Access.Layer.Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Layer.Abstraction;
using System;
using System.Collections.Generic;
using System.Linq;

namespace User.Interface.Layer.Controllers
{
    public class ReportController : Controller
    {
        private readonly ILogger<ReportController> _logger;
        private IUnitOfWork _uOw;

        public ReportController(ILogger<ReportController> logger, IUnitOfWork uOw)
        {
            _logger = logger;
            _uOw = uOw;
        }
        // GET: ReportController
        public ActionResult Index()
        {
            IEnumerable<BookTransactions> bookTransactions = _uOw.BookTransactionRepository.GetAllWithBooksAndMembersForPredicateAsync().GetAwaiter().GetResult().Where(x => x.ReturnDate.Subtract(DateTime.Today).Days <= 2 || DateTime.Today.Subtract(x.ReturnDate).Days < 0).ToList();
            _uOw.Dispose();
            return View(bookTransactions);
        }
    }
}

LibraryWebApplication/User.Interface.Layer/Controllers/SearchController.cs
using Data.Access.Layer.Classes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Layer.Abstraction;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using User.Interface.Layer.Models;

namespace User.Interface.Layer.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger<SearchController> _logger;
        private IUnitOfWork _uOw;

        public SearchController(ILogger<SearchController> logger, IUnitOfWork uOw)
        {
            _logger = logger;
            _uOw = uOw;
        }
        // GET: SearchController
        public ActionResult Index()
        {
            SearchViewModel searchViewModel = new();
            searchViewModel.Authors = _uOw.AuthorRepository.GetAllAsync().GetAwaiter().GetResult();
            return View(searchViewModel);
        }
        // POST: SearchController/Search
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchViewModel searchViewModel)
        {
            IEnumerable<Books> books = _uOw.BookRepository.GetAllAsync().GetAwaiter().GetResult();
            books = books.Where(x => x.Name.Contains(searchViewModel.Name ?? "***") || x.LoanDate.Year == searchViewModel.LoanDate.Year || x.AuthorID == searchViewModel.AuthorId || x.ISBN == searchViewModel.ISBN).ToList();
            _uOw.Dispose();
            return View(books);
        }
    }
}

LibraryWebApplication/User.Interface.Layer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library Web Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library Web Application</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rezervations" asp-action="Index">Rezervations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Report</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Library Web Application
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>