LibraryWebApplication/User.Interface.Layer/Models/SearchViewModel.cs
using Data.Access.Layer.Classes;
using System;
using System.Collections.Generic;

namespace User.Interface.Layer.Models
{
    public class SearchViewModel
    {
        public string Name { get; set; }
        public int ISBN { get; set; }
        public DateTime LoanDate { get; set; }
        public int AuthorId { get; set; }
        public IEnumerable<Authors> Authors { get; set; }
    }
}

LibraryWebApplication/User.Interface.Layer/Controllers/BooksController.cs
using Data.Access.Layer.Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Layer.Abstraction;
using System.Collections.Generic;

namespace User.Interface.Layer.Controllers
{
    public class BooksController : Controller
    {
        private readonly ILogger<BooksController> _logger;
        private IUnitOfWork _uOw;

        public BooksController(ILogger<BooksController> logger, IUnitOfWork uOw)
        {
            _logger = logger;
            _uOw = uOw;
        }
        // GET: BooksController
        public ActionResult Index()
        {
            IEnumerable<Books> books = _uOw.BookRepository.GetAllWithAuthorAsync().GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(books);
        }

        // GET: BooksController/Details/5
        public ActionResult Details(int id)
        {
            Books book = _uOw.BookRepository.GetByIdWithAuthorAsync(id).GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(book);
        }

        // GET: BooksController/Create
        public ActionResult Create()
        {
            ViewBag.Authors = _uOw.AuthorRepository.GetAllAsync().GetAwaiter().GetResult();
            return View();
        }

        // POST: BooksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Books book)
        {
            try
            {
                _uOw.BookRepository.AddAsync(book).GetAwaiter().GetResult();
                _uOw.CommitAsync().GetAwaiter().GetResult();
                _uOw.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BooksController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Authors = _uOw.AuthorRepository.GetAllAsync().GetAwaiter().GetResult();
            Books book = _uOw.BookRepository.GetByIdAsync(id).GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(book);
        }

        // POST: BooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Books book)
        {
            try
            {
                _uOw.BookRepository.UpdateAsync(book).GetAwaiter().GetResult();
                _uOw.CommitAsync().GetAwaiter().GetResult();
                _uOw.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryWebApplication/User.Interface.Layer/Controllers/RezervationsController.cs
using Data.Access.Layer.Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Layer.Abstraction;
using System;
using System.Collections.Generic;

namespace User.Interface.Layer.Controllers
{
    public class RezervationsController : Controller
    {
        private static int updatedBookId;
        private readonly ILogger<RezervationsController> _logger;
        private IUnitOfWork _uOw;

        public RezervationsController(ILogger<RezervationsController> logger, IUnitOfWork uOw)
        {
            _logger = logger;
            _uOw = uOw;
        }
        // GET: RezervationController
        public ActionResult Index()
        {
            IEnumerable<BookTransactions> bookTransactions = _uOw.BookTransactionRepository.GetAllWithBooksAndMembersAsync().GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(bookTransactions);
        }

        // GET: RezervationController/Details/5
        public ActionResult Details(int id)
        {
            BookTransactions bookTransaction = _uOw.BookTransactionRepository.GetAllWithBooksAndMembersByIdAsync(id).GetAwaiter().GetResult();
            _uOw.Dispose();
            return View(bookTransaction);
        }

        // GET: RezervationController/Create
        public ActionResult Create()
        {
            ViewBag.Books = _uOw.BookRepository.Find(x => x.StockQuantity > 0).GetAwaiter().GetResult();
            ViewBag.Members = _uOw.MemberRepository.GetAllAsync().GetAwaiter().GetResult();
            _uOw.Dispose();
            return View();
        }

        // POST: RezervationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookTransactions bookTransaction)
        {
            try
            {
                Books book = _uOw.BookRepository.GetByIdAsync(bookTransaction.BookID).GetAwaiter().GetResult();
                if (book.StockQuantity > 0)
                {
                    _uOw.BookTransactionRepository.AddAsync(bookTransaction).GetAwaiter().GetResult();
                    bookTransaction.Book.StockQuantity--;
                    _uOw.BookRepository.UpdateAsync(bookTransaction.Book).GetAwaiter().GetResult();
                    _uOw.CommitAsync().GetAwaiter().GetResult();
                    _uOw.Dispose();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    throw new Exception($"Sorry. We dont have this book enough!");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: RezervationController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Books = _uOw.BookRepository.Find(x => x.StockQuantity > 0).GetAwaiter().GetResult();
            ViewBag.Members = _uOw.MemberRepository.GetAllAsync().GetAwaiter().GetResult();
            BookTransactions bookTransaction = _uOw.BookTransactionRepository.GetByIdAsync(id).GetAwaiter().GetResult();
            updatedBookId = bookTransaction.BookID;
            _uOw.Dispose();
            return View(bookTransaction);
        }

        // POST: RezervationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BookTransactions bookTransaction)
        {
            try
            {
                Books book = _uOw.BookRepository.GetByIdAsync(bookTransaction.BookID).GetAwaiter().GetResult();
                if (book.StockQuantity > 0)
                {
                    _uOw.BookTransactionRepository.UpdateAsync(bookTransaction).GetAwaiter().GetResult();
                    if (updatedBookId != bookTransaction.BookID)
                    {
                        bookTransaction.Book.StockQuantity--;
                        _uOw.BookRepository.UpdateAsync(bookTransaction.Book).GetAwaiter().GetResult();
                        Books updatedBook = _uOw.BookRepository.GetByIdAsync(updatedBookId).GetAwaiter().GetResult();
                        updatedBook.StockQuantity++;
                        _uOw.BookRepository.UpdateAsync(updatedBook);
                    }
                    _uOw.CommitAsync().GetAwaiter().GetResult();
                    _uOw.Dispose();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    throw new Exception($"Sorry. We dont have this book enough!");
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryWebApplication/User.Interface.Layer/Controllers/SearchController.cs
using Data.Access.Layer.Classes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services.Layer.Abstraction;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using User.Interface.Layer.Models;

namespace User.Interface.Layer.Controllers
{
    public class SearchController : Controller
    {
        private readonly ILogger<SearchController> _logger;
        private IUnitOfWork _uOw;

        public SearchController(ILogger<SearchController> logger, IUnitOfWork uOw)
        {
            _logger = logger;
            _uOw = uOw;
        }
        // GET: SearchController
        public ActionResult Index()
        {
            SearchViewModel searchViewModel = new();
            searchViewModel.Authors = _uOw.AuthorRepository.GetAllAsync().GetAwaiter().GetResult();
            return View(searchViewModel);
        }
        // POST: SearchController/Search
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchViewModel searchViewModel)
        {
            IEnumerable<Books> books = _uOw.BookRepository.GetAllAsync().GetAwaiter().GetResult();
            books = books.Where(x => x.Name.Contains(searchViewModel.Name ?? "***") || x.LoanDate.Year == searchViewModel.LoanDate.Year || x.AuthorID == searchViewModel.AuthorId || x.ISBN == searchViewModel.ISBN).ToList();
            _uOw.Dispose();
            return View(books);
        }
    }
}

LibraryWebApplication/User.Interface.Layer/Views/Search/Index.cshtml
@model SearchViewModel;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Search</h1>

<h4>Search For Books</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" placeholder="Book Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" placeholder="Book Name" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Authors" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control" asp-items="@(new SelectList(Model.Authors, "ID", "FullName"))">
                    <option>Authors</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="LoanDate" class="control-label"></label>
                <input type="date" asp-for="LoanDate" class="form-control" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

LibraryWebApplication/User.Interface.Layer/Views/Search/Search.cshtml
@model List<Data.Access.Layer.Classes.Books>;

@{
    ViewData["Title"] = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    for (int i = 0; i < Model.Count(); i++)
    {
        <div class="card">
            <div class="card-body">
                <ul class="navbar-nav flex-grow-1 text-right">
                    <li class="nav-item">
                        <a class="nav-link text-primary" asp-area="" asp-controller="Books" asp-action="Edit" asp-route-id="@Model[i].ID">Edit Book</a>
                    </li>
                </ul>
                <h4 class="card-title">@Model[i].Name - @Model[i].ISBN</h4>
                <p class="card-text">Loan Date: @Model[i].LoanDate.ToShortDateString()</p>
                <p class="card-text">Stock Quantity: @Model[i].StockQuantity</p>
                <a class="btn btn-primary" asp-area="" asp-controller="Books" asp-action="Details" asp-route-id="@Model[i].ID">See Details</a>
                <a class="btn btn-primary" asp-area="" asp-controller="Rezervations" asp-action="Create">Create Rezervation</a>
            </div>
        </div>
    }
}